
services:
  postgres:
    image: postgres:latest
    restart: always
    container_name: postgresdb
    environment:
      POSTGRES_DB: "counter_db"
      POSTGRES_USER: "counter_user"
      POSTGRES_PASSWORD: "counter_password"
    ports:
      - "5432:5432"
    volumes:
      - db:/data:/var/lib/postgresql/data

  counter_app:
    container_name: counter_app
    build: 
      context: .
      dockerfile: Dockerfile
    ports:
      - "8501:8501"
    depends_on:
      - postgres
    environment:
      database_host: postgresdb


volumes:
  db: